mysite/home/urls.py
from django.urls import path 
from . import views
from django.conf.urls import static
from django.conf import settings


urlpatterns = [
    path('reservation',views.ReservationView.as_view(),name='reservation'),
    path('',views.IndexView.as_view(), name="index"),
    path('reservationUpdate/<int:pk>/',views.ReservationUpdate.as_view(),name='reservationUpdate'),
    path('reservationDelete/<int:pk>/',views.ReservationDelete.as_view(),name='reservationDelete'),
    path('review',views.ReviewView.as_view(),name="review"),
    path('reviewUpdate/<int:pk>/',views.ReviewUpdateView.as_view(),name="review_update"),
    path('reviewDelete/<int:pk>/',views.ReviewDelete.as_view(),name="review_delete"),
    path('blog',views.BlogView.as_view(), name="blog"),
    path('blogUpdate/<int:pk>/',views.BlogUpdateView.as_view(),name="blog_update"),
    path('blogDelete/<int:pk>/',views.BlogDeleteView.as_view(),name="blog_delete"),
    path('baseView',views.BaseView.as_view(),name="base_cart"),
]

mysite/menu/urls.py
from django.urls import reverse_lazy, include, path
from . import views

app_name = 'menu'
urlpatterns = [
    path('createDish',views.AddDish.as_view(),name='createDish'),
    path('menuList',views.MenuView.as_view(),name='menuList'),
    path('updateDish/<int:pk>/',views.UpdateDish.as_view(), name='updateDish'),
    path('deleteDish/<int:pk>/', views.DeleteDish.as_view(), name='deleteDish'),
    path('addtoCart/<int:dish_id>/', views.AddToCartView.as_view(), name="addtoCart"),
    path('remove/<int:pk>/', views.RemoveFromCart.as_view(), name='remove_from_cart'),
    path('quantityUpdate/<int:item_id>/', views.QuantityUpdateView.as_view(), name='quantityUpdate'),
    path('view_cart', views.CartView.as_view(), name='view_cart'),
    path('error', views.ErrorView.as_view(), name="error"),
    path('suggestions',views.AddSuggestions.as_view(), name="addsuggestions"),
    path('suggUpdate/<int:pk>/',views.SuggestionUpdateView.as_view(),name="sugg_update"),
    path('suggDelete/<int:pk>/',views.SuggestionDeleteView.as_view(),name="sugg_delete"),
    path('search/', views.SearchResultsView.as_view(), name='search'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [

    path('',include("home.urls"), name="index"),
    path('dj-admin/', admin.site.urls),
    path('admin/',include('customadmin.urls')),
    path('menu/',include("menu.urls", namespace='menu')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('cked/', include('cked.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/menu/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User

class Countries(models.Model):
    countries=models.CharField(max_length=100)

    def __str__(self):
        return self.countries
    
class Dish(models.Model):
    name= models.CharField(max_length=100)
    description=models.TextField()
    price=models.FloatField()
    image=models.CharField(max_length=200)
    country_of_origin=models.ForeignKey(Countries, on_delete=models.CASCADE)

    def __str__(self):
            return self.name



class CartItem(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE, default=None, null=True)
    dish=models.ForeignKey('Dish',on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=0)
    date_added=models.DateTimeField(auto_now_add=True, null=True)
    total_amount = models.FloatField(default=0.0)
    message=models.CharField(max_length=200 ,default="Please Wait! We are processing your Order")
    is_accepted= models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)
    

class UserSuggestions(models.Model):
    name= models.CharField(max_length=200)
    description=models.TextField()
    price=models.FloatField()
    image=models.CharField(max_length=200)
    user= models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    accepted= models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

mysite/menu/forms.py
from django import forms
from . models import Dish, CartItem, UserSuggestions


class DishForm(forms.ModelForm):
    class Meta:
        model=Dish 
        fields='__all__'

    def __init__(self,*args,**kwargs):
        super(DishForm,self).__init__(*args,**kwargs)
        self.fields['country_of_origin'].empty_label="SELECT"

class searchForm(forms.Form): 
    query=forms.CharField(label='Search')

class cartForm(forms.ModelForm):
    class Meta:
        model= CartItem
        fields=['quantity']

class UserSuggestionsForm(forms.ModelForm):
    name = forms.CharField(label='What is the name of your dish?')
    description = forms.CharField(label='Describe your dish', widget=forms.Textarea)
    price = forms.FloatField(label='Price of the dish (in $)')
    image = forms.CharField(label='URL of the dish image')

    class Meta:
        model = UserSuggestions
        fields = ['name','description','price','image']
    
    

mysite/menu/views.py
from django.http import HttpRequest
from django.http.response import HttpResponse, HttpResponseRedirect
from django.views.generic import View
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView,  ListView, TemplateView, UpdateView, DeleteView, RedirectView
from . models import Dish, UserSuggestions
from .forms import DishForm,searchForm,cartForm, UserSuggestionsForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .models import Dish, CartItem
from django.contrib.auth.models import User
import logging

logger = logging.getLogger(__name__)

class ErrorView(TemplateView):
    template_name="home_folder/error.html"

class AddSuggestions(LoginRequiredMixin, CreateView):
    form_class= UserSuggestionsForm
    template_name = 'home_folder/somethingelse.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user 
        context["usersuggestions"] = UserSuggestions.objects.filter(user=self.request.user)
        query = self.request.GET.get('q', '')
        if query:
            context['dishes'] = Dish.objects.filter(name__icontains=query)
        else:
            context['dishes'] = Dish.objects.all()
        context['query'] = query 
        return context

class SearchResultsView(ListView):
    model = Dish
    template_name = 'home_folder/search_result.html'
    context_object_name = 'dishes'

    def get_queryset(self):
        search_query = self.request.GET.get('q', '')
        return Dish.objects.filter(name__icontains=search_query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('q', '')
        # print(context['dishes'])
        return context
    
class SuggestionUpdateView(UpdateView):
    model= UserSuggestions
    form_class= UserSuggestionsForm
    template_name="home_folder/somethingelse.html"
    success_url = reverse_lazy('menu:addsuggestions')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['usersuggestions'] = UserSuggestions.objects.filter(user=self.request.user)
        return context

class SuggestionDeleteView(DeleteView):
    model= UserSuggestions
    template_name= "home_folder/delete.html"
    success_url = reverse_lazy("menu:addsuggestions")
    
class AddDish(UserPassesTestMixin, CreateView):
    model = Dish
    form_class = DishForm
    template_name = 'home_folder/alldish.html'
    success_url = reverse_lazy('menu:createDish')

    def test_func(self):
        return self.request.user.is_superuser
    
    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('menu:addsuggestions')
        else:
            return super().handle_no_permission()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q', '')
        if query:
            context['dishes'] = Dish.objects.filter(name__icontains=query)
        else:
            context['dishes'] = Dish.objects.all()
        context['query'] = query
        return context
    
class UpdateDish(UpdateView):
    model=Dish 
    form_class=DishForm
    template_name="home_folder/alldish.html"
    success_url= reverse_lazy('menu:createDish')

class DeleteDish(DeleteView):
    model=Dish
    template_name="home_folder/delete.html"
    success_url=reverse_lazy('menu:createDish')

class MenuView(ListView):
    model= Dish
    template_name='home_folder/menu.html'

    def get_context_data(self, **kwargs):
        context= super(). get_context_data(**kwargs)
        context['dishes']=self.get_queryset()
        return context  

class AddToCartView(View):
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('login'))
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, dish_id):
        dish = Dish.objects.get(id=dish_id)

        cart_item, created = CartItem.objects.get_or_create(
            dish=dish, 
            user=request.user,
            defaults={'quantity': 1}
        )
        if not created:
            cart_item.quantity += 1
            cart_item.save()
        cart_item.total_amount = cart_item.quantity* dish.price
        cart_item.save()
        return redirect('menu:view_cart')

class RemoveFromCart(DeleteView):
    model=CartItem
    template_name="home_folder/delete.html"
    success_url=reverse_lazy('menu:view_cart')
    

class CartView(LoginRequiredMixin, CreateView):
    template_name = 'home_folder/cart.html'
    form_class = cartForm
    success_url = reverse_lazy('menu:view_cart')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_items'] = CartItem.objects.filter(user=self.request.user)
        print(context['cart_items'])
        context['total_price'] = sum(item.dish.price * item.quantity for item in context['cart_items'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class QuantityUpdateView(UpdateView):
    model = CartItem
    form_class = cartForm
    template_name = "home_folder/cart.html"
    success_url = reverse_lazy('menu:menuList')

    def get_object(self, queryset=None):
        return get_object_or_404(CartItem, id=self.kwargs['item_id'])

mysite/templates/home_folder/auth-login.html
{%load static%}
<!doctype html>
<html lang="en">

    <head>
        
        <meta charset="utf-8" />
        <title>Login | Assets MS</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">

        <!-- Bootstrap Css -->
        <link href="{% static 'assets2/css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets2/css/icons.min.css'%}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'assets2/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

    </head>

    <body class="bg-pattern">
        <div class="bg-overlay"></div>
        <div class="account-pages my-5 pt-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-4 col-lg-6 col-md-8">
                        <div class="card">
                            <div class="card-body p-4">
                                <div class="">
                                    <div class="text-center">
                                        <a href="index.html" class="">
                                            <img src="{% static 'assets2/images/logo-dark.png'%}" alt="" height="24" class="auth-logo logo-dark mx-auto">
                                            <img src="{% static 'assets2/images/logo-light.png'%}" alt="" height="24" class="auth-logo logo-light mx-auto">
                                        </a>
                                    </div>
                                    <!-- end row -->
                                    <h4 class="font-size-18 text-muted mt-2 text-center">Welcome Back !</h4>
                                    <p class="mb-5 text-center">Sign in to continue.</p>
                                    {%if user.is_staff is false%}
                                    <p>You must be a superuser or a staff to login.</p>
                                    {%endif%}
                                    <form class="form-horizontal" method='post' action="{% url 'admin_login'%}">
                                        {%csrf_token%}
                                        {{form.as_p}}
                                        <button type="submit">Submit</button>
                                    </form>
                                    <div style="display:flex; justify-content:between;">
                                        <p>Don't have an account?</p>
                                        <a href="{%url 'admin_register'%}">Register</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        </div>
        <!-- end Account pages -->

        <!-- JAVASCRIPT -->
        <script src="{% static 'assets2/libs/jquery/jquery.min.js'%}"></script>
        <script src="{% static 'assets2/libs/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
        <script src="{% static 'assets2/libs/metismenu/metisMenu.min.js'%}"></script>
        <script src="{% static 'assets2/libs/simplebar/simplebar.min.js'%}"></script>
        <script src="{% static 'assets2/libs/node-waves/waves.min.js'%}"></script>

        <script src="{% static 'assets2/js/app.js'%}"></script>

    </body>
</html>

mysite/templates/home_folder/base.html
{%load static%}
{% load bootstrap5 %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rescaf - Food & Restauratn Template</title>

    <!-- ========== Favicon Icon ========== -->

        
        <!-- jvectormap -->
        <link href="{% static 'assets2/libs/jqvmap/jqvmap.min.css' %}" rel="stylesheet" />

        <!-- Bootstrap Css -->
        <link href="{% static 'assets2/css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'assets2/css/icons.min.css'%}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'assets2/css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    <!-- ========== End Stylesheet ========== -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5/html5shiv.min.js"></script>
      <script src="assets/js/html5/respond.min.js"></script>
    <![endif]-->

    <!-- ========== Google Fonts ========== -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,500,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


    {% bootstrap_css %}
{% bootstrap_javascript %}

</head>
    <body>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Rescaf</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
              <div class="d-flex flex-grow-1 justify-content-center">
                <form class="d-flex" action="{% url 'menu:search' %}" method="get" id="search_form">
                    <input class="form-control me-2" type="text" name="q" id="search_query" placeholder="Enter dish name">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
                <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"><i class="bi bi-cart"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
                </svg></i></button>
            </div>
        </div>
    </nav>

    <div class="offcanvas offcanvas-end" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasRightLabel">Your Cart</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Item</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
              </tr>
            </thead>
            <tbody>
              {%for cart in cart_items%}
              <tr>
                <th scope="row">{{foorloop.counter}}</th>
                <td>{{cart.dish.name}}</td>
                <td>{{cart.quantity}}</td>
                <td>{{cart.dish.price}}</td>
              </tr>
              {%endfor%}
            </tbody>
            <p>Total Cost:{{total_price}}</p>
            <a href="{%url 'menu:view_cart'%}">Proceed To Checkout</a>
          </table>
        </div>
        
        </div>
    </div>
    <div class="OrderFormList container-fluid" style="display: flex; justify-content:center;">
        <div class="form">{%block content%} {%endblock%} {%block list%}{%endblock%}</div>
    </div>
    <!-- End Breadcrumb -->
    <!--Footer container-->
<!-- Footer container -->
<!-- Remove the container if you want to extend the Footer to full width. -->


  <footer style="background-color: #deded5;">
  <div class="container-fluid p-4">
    <div class="row">
      <div class="col-lg-6 col-md-12 mb-4">
        <h5 class="mb-3" style="letter-spacing: 2px; color: #818963;">footer content</h5>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
          molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
          voluptatem veniam, est atque cumque eum delectus sint!
        </p>
      </div>
      <div class="col-lg-3 col-md-6 mb-4">
        <h5 class="mb-3" style="letter-spacing: 2px; color: #818963;">links</h5>
        <ul class="list-unstyled mb-0">
          <li class="mb-1">
            <a href="#!" style="color: #4f4f4f;">Frequently Asked Questions</a>
          </li>
          <li class="mb-1">
            <a href="#!" style="color: #4f4f4f;">Delivery</a>
          </li>
          <li class="mb-1">
            <a href="#!" style="color: #4f4f4f;">Pricing</a>
          </li>
          <li>
            <a href="#!" style="color: #4f4f4f;">Where we deliver?</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-3 col-md-6 mb-4">
        <h5 class="mb-1" style="letter-spacing: 2px; color: #818963;">opening hours</h5>
        <table class="table" style="color: #4f4f4f; border-color: #666;">
          <tbody>
            <tr>
              <td>Mon - Fri:</td>
              <td>8am - 9pm</td>
            </tr>
            <tr>
              <td>Sat - Sun:</td>
              <td>8am - 1am</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- End of .container -->
    <!-- jQuery Frameworks
    ============================================= -->
    <!-- JAVASCRIPT -->
    <script src="{% static 'assets2/libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets2/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets2/libs/metismenu/metisMenu.min.js' %}"></script>
    <script src="{% static 'assets2/libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static 'assets2/libs/node-waves/waves.min.js' %}"></script>

    <!-- apexcharts js -->
    <script src="{% static 'assets2/libs/apexcharts/apexcharts.min.js' %}"></script>

    <!-- jquery.vectormap map -->
    <script src="{% static 'assets2/libs/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'assets2/libs/jqvmap/maps/jquery.vmap.usa.js' %}"></script>

    <script src="{% static 'assets2/js/pages/dashboard.init.js' %}"></script>
    <script>
        $(document).ready(function() {
            $("#MyModal").modal();
          });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>

    <script src="{% static 'assets2/js/app.js' %}"></script>
</body>
</html>

mysite/templates/home_folder/basedish.html
{%extends "home_folder/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {%endblock}</title>
</head>
<body>
    {% block dish_list %} {%endblock%}
    
</body>
</html>

mysite/templates/home_folder/cuisine_confirm_delete.html
{%load static%}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>success</p>
    <a href="{%url 'list'%}">Go back to list</a>
    
</body>
</html>

mysite/templates/home_folder/error.html
<p>error</p>

mysite/templates/home_folder/review.html
{% extends 'home_folder/base.html' %}

{% block content %}
<style>
    form {
        background-color: #f8f9fa; /* Light background color */
    }
    
    form .form-control {
        border-radius: 5px;
    }
    
    form .btn {
        border-radius: 5px;
    }
</style>

<div class="container-fluid py-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8 text-center">
            <h3 class="fw-bold mb-4">Menu</h3>
            <p class="mb-4 pb-2 mb-md-5 pb-md-0">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error amet
                numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum
                quisquam eum porro a pariatur veniam.
            </p>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-md-6 mb-5">
            <h2 class="mb-4">Write a Review</h2>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-2">Submit</button>
            </form>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-md-8">
            <h2 class="mb-4">Reviews that you've left in the past</h2>
            <div class="user-review-list">
                {% for review in user_reviews %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ review.dish.name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Rated: {{ review.stars }} Stars</h6>
                        <p class="card-text">{{ review.description }}</p>
                        <p class="card-text"><small class="text-muted">By: {{ review.user }}</small></p>
                        <a class="image-button" href="{% url 'review_update' review.id %}">Update</a>
                        <a class="delete-button" href="{% url 'review_delete' review.id %}">Delete</a>
                    </div>
                </div>
                {% empty %}
                <p>No reviews found.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/home_folder/somethingelse.html
{% extends 'home_folder/base.html' %} {% load static %}
<div>
  {% block content %}
  <h3>Give us your suggestion.</h3>
  <form action="" method="post" id="create_form">
    {% csrf_token %} {{ form }}
    <div>
      <button type="submit" id="submit_create">Submit</button>
    </div>
  </form>
</div>
{% endblock %}
<div>
  {% block list %}
  <div>
    <h2>Want another check?</h2>
    <p>Check if the dish you are adding is already present in our catalogue.</p>
    <form action="" method="get" id="search_form">
      <label for="search_query">Search by Name:</label>
      <input
        type="text"
        name="q"
        id="search_query"
        placeholder="Enter dish name"
      />
      <button type="submit">Search</button>
    </form>
    {% if request.GET.q %}
    <h2 class="search-header">Search Results for "{{ request.GET.q }}"</h2>
    <div class="item-card">
      {% for dish in dishes %}
      <div class="dish-card">
        <img src="{{ dish.image }}" alt="image" class="dish-image" />
        <div class="card-content">
          <h2 class="dish-name">{{ dish.name }}</h2>
          <p class="dish-description">{{ dish.description }}</p>
          <p class="dish-price">
            <span class="price-tag">$</span>{{ dish.price }}
          </p>
          <div class="button-container">
            <a class="image-button" href="{%url 'menu:updateDish' dish.id%}"
              >Update</a
            >
            <a
              class="delete-button"
              method="post"
              href="{%url 'menu:deleteDish' dish.id %}"
              >Delete</a
            >
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    {% endif %}
  </div>
</div>
<div>
  <h3>Previous dish additions that you've made:</h3>
  {% for usersug in usersuggestions %}
  <div class="dish-card">
    <img src="{{ usersug.image }}" alt="image" class="dish-image" />
    <div class="card-content">
      <h2 class="dish-name">{{ usersug.name }}</h2>
      <p class="dish-description">{{ usersug.description }}</p>
      <p class="dish-price">
        <span class="price-tag">$</span>{{ usersug.price }}
      </p>
      <p class="dish-price">
        <span class="price-tag">
          {% if usersug.accepted is False %}
          <span class="price-tag">Status:Not Accepted (Waiting)</span>
          {% else %}
          <span class="price-tag">Status:Accepted</span>
          {% endif %}
        </span>
      </p>

      <div class="button-container">
        <a class="image-button" href="{%url 'menu:sugg_update' usersug.id%}"
          >Update</a
        >
        <a
          class="delete-button"
          method="post"
          href="{%url 'menu:sugg_delete' usersug.id %}"
          >Delete</a
        >
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}